 // This file is generated by src/lib/app.ts
import * as _404 from './src/pages/404.tsx';
import * as _index from './src/pages/index.tsx';
import * as _net from './src/pages/net.tsx';
import * as _net_server from './src/pages/net.server.ts';
import * as _todos from './src/pages/todos.tsx';

export const modules = {
    _404,
    _index,
    _net,
    _net_server,
    _todos
};
