 // This file is generated by src/lib/app.ts
import _404 from './src/pages/404.tsx';
import _index from './src/pages/index.tsx';
import _todos from './src/pages/todos.tsx';

export const modules = {
    _404,
    _index,
    _todos
};
