import { servePageModule } from '@/lib/server/servePageModule.ts';
import { serveDir } from 'std/http/file_server.ts';
import { ModuleMap } from '@/lib/types.ts';
import { normalize } from 'std/path/posix.ts';
import { blue, green, yellow } from 'std/fmt/colors.ts';
import { Status } from 'std/http/http_status.ts';
import { serveServerModule } from '@/lib/server/serveServerModule.ts';
import { isDev } from '@/lib/server/env.ts';
import { bundle } from '@/lib/server/bundle.ts';

export const createRouter = async (modules: ModuleMap) => {
    if (isDev) await generateModules();
    const bundledFiles = await bundle();

    return async (req: Request): Promise<Response> => {
        const url = new URL(req.url);

        if (url.pathname.startsWith('/api')) { // If is an API request
            const res = await serveServerModule(modules, req);
            log(req, res, 'api');
            return res;
        }
        if (req.method !== 'GET') { // Only allow GET requests past this point
            const res = new Response('Method not allowed', { status: Status.MethodNotAllowed });
            log(req, res);
            return res;
        }
        if (url.pathname.includes('.')) { // If has a file extension
            const res = await serveDir(req, { fsRoot: './public', urlRoot: '', quiet: true });
            log(req, res, 'file');
            return res;
        }

        // If is a page request
        const { html, status } = await servePageModule(modules, url, bundledFiles);
        const res = new Response(new TextEncoder().encode(html), { status });
        log(req, res, 'page');
        return res;
    };
};

async function generateModules() {
    const importStr: string[] = [];
    const exportStr: string[] = [];
    // Get all modules from pages dir
    for await (const dirEntry of Deno.readDir('./src/pages')) {
        if (!dirEntry.isFile) break;
        const name = dirEntry.name.replace(/\.[^/.]+$/, '');
        const modName = name.replace('.', '_');
        importStr.push(`import * as _${modName} from './src/pages/${dirEntry.name}';`);
        exportStr.push(`_${modName}`);
    }

    const file = ` // This file is generated by src/lib/app.ts
${importStr.sort().join('\n')}

export const modules = {
    ${exportStr.sort().join(',\n    ')}
};
`;

    try {
        const currentFile = await Deno.readTextFile('./modules.gen.ts');
        const hasChanged = currentFile !== file;

        if (!hasChanged) return;
    } catch {
        // Ignore error, we'll just write the file
    }
}

function log(req: Request, res: Response, type = 'other') {
    const d = new Date().toISOString();
    const dateFmt = `${d.slice(0, 10)} ${d.slice(11, 19)}`;
    const normalizedUrl = normalize(decodeURIComponent(new URL(req.url).pathname));
    let s = `[${dateFmt}] [${req.method}] [${type}] ${normalizedUrl} ${res.status}`;

    switch (type) {
        case 'page':
            s = blue(s);
            break;
        case 'file':
            s = yellow(s);
            break;
        case 'api':
            s = green(s);
            break;
    }

    console.debug(s);
}
